# Generated by Django 4.0.3 on 2022-05-08 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_classes_prereq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('standing', models.IntegerField(default=1)),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree', to='product.program')),
            ],
            options={
                'ordering': ('lastname',),
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='program',
            field=models.ManyToManyField(to='product.program'),
        ),
    ]
