# Generated by Django 4.0.3 on 2022-05-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_program_student_classes_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(default='Computer Science UG', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree', to='product.program'),
        ),
    ]
