# Generated by Django 4.0.3 on 2022-05-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_student_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree', to='product.program'),
        ),
    ]
