# Generated by Django 4.0.3 on 2022-04-17 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('standing', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=10, null=True)),
                ('coreq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coreqclass', to='product.classes')),
                ('prereq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prereqclass', to='product.classes')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
