# Generated by Django 4.0.3 on 2022-04-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_department_alter_classes_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='units',
            field=models.IntegerField(default=3),
        ),
    ]
