# Generated by Django 4.0.3 on 2022-04-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_classes_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='coreq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coreqclass', to='product.classes'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='prereq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prereqclass', to='product.classes'),
        ),
    ]
