# Generated by Django 4.0.3 on 2022-05-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_student_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='blank@cpp.edu', max_length=254),
        ),
    ]
